### ISSUE TITLE
Justin es gay

### ISSUE THREAD

**Issue by Uriegas** [AgustinZavalaA/ClasesDoc#1]
🐸👌
![gameover](https://user-images.githubusercontent.com/56318374/113479359-df046f80-944b-11eb-9573-1facd394d0c4.png)

**Comment by AgustinZavalaA** [comment]
XD

**Comment by Uriegas** [comment]
Ala, te pasaste de lanza. Pa que lo cierras. Te recomiendo que implementes este codigo compañero:
```matlab
a = ' es gay';
J = 'Justin';
disp(strcat(J,a))
```

**Comment by AgustinZavalaA** [comment]
El issue esta cerrado compañero, lo considerare en commits mas adelante, gracias por tu apoyo.

**Comment by Uriegas** [comment]
De nada. Arigato Gozaimas. Konichiwa. 
> Este mensaje ha sido enviado desde un iPhone 16 6G
